### ISSUE TITLE
运行报错了

### ISSUE THREAD

**Issue by eicky** [yulewang/cloudflare-api-v4-ddns#5]
```
Updating zone_identifier & record_identifier
Updating DNS to 1.1.1.1
cf-v4-ddns.sh: line 140: [: !=: unary operator expected
Something went wrong :(
Response: {
  "result": {
    "id": "e11ce34e68aab16cdc2a93a690cb5935",
    "zone_id": "9fca16d42d77e6f2336df8059a021193",
    "zone_name": "xx.ltd",
    "name": "azure.xx.ltd",
    "type": "A",
    "content": "1.1.1.1",
    "proxiable": true,
    "proxied": false,
    "ttl": 120,
    "locked": false,
    "meta": {
      "auto_added": false,
      "managed_by_apps": false,
      "managed_by_argo_tunnel": false,
      "source": "primary"
    },
    "created_on": "2020-03-14T10:18:03.449524Z",
    "modified_on": "2020-03-14T10:18:03.449524Z"
  },
  "success": true,
  "errors": [],
  "messages": []
}
```

应该是解析json出错了

**Comment by Scholar-m** [comment]
./cf-v4-ddns.sh: 第 140 行:[: !=: 期待一元表达式
Something went wrong :(
Response: {
  "result": null,
  "success": false,
  "errors": [
    {
      "code": 81044,
      "message": "The record does not exist."
    }
  ],
  "messages": []
}

**Comment by Scholar-m** [comment]
Updating DNS to 1.1.1.1
./cf-v4-ddns.sh: 第 140 行:[: !=: 期待一元表达式
Something went wrong :(
Response: {
  "result": {
    "id": "xxx",
    "zone_id": "xxx",
    "zone_name": "xxxx.link",
    "name": "xxxx.link",
    "type": "A",
    "content": "1.1.1.1",
    "proxiable": true,
    "proxied": false,
    "ttl": 120,
    "locked": false,
    "meta": {
      "auto_added": false,
      "managed_by_apps": false,
      "managed_by_argo_tunnel": false,
      "source": "primary"
    },
    "created_on": "2020-03-24T14:30:03.716054Z",
    "modified_on": "2020-03-24T14:30:03.716054Z"
  },
  "success": true,
  "errors": [],
  "messages": []
}

**Comment by eicky** [comment]
> Updating DNS to 1.1.1.1
> ./cf-v4-ddns.sh: 第 140 行:[: !=: 期待一元表达式
> Something went wrong :(
> Response: {
> "result": {
> "id": "xxx",
> "zone_id": "xxx",
> "zone_name": "xxxx.link",
> "name": "xxxx.link",
> "type": "A",
> "content": "1.1.1.1",
> "proxiable": true,
> "proxied": false,
> "ttl": 120,
> "locked": false,
> "meta": {
> "auto_added": false,
> "managed_by_apps": false,
> "managed_by_argo_tunnel": false,
> "source": "primary"
> },
> "created_on": "2020-03-24T14:30:03.716054Z",
> "modified_on": "2020-03-24T14:30:03.716054Z"
> },
> "success": true,
> "errors": [],
> "messages": []
> }

咋修改呢，不会shell脚本，求修改

**Comment by WilliamXie9** [comment]
> ./cf-v4-ddns.sh: 第 140 行:[: !=: 期待一元表达式
> Something went wrong :(
> Response: {
> "result": null,
> "success": false,
> "errors": [
> {
> "code": 81044,
> "message": "The record does not exist."
> }
> ],
> "messages": []
> }

遇到这个错误了，请问是什么原因呢？

**Comment by qiangwushuang** [comment]
同样遇到这个问题

**Comment by qiangwushuang** [comment]
> 同样遇到这个问题

找到原因，如果手动删除cloudflare中的dns记录然后重新创建，会导致RECORD_ID变化，因为脚本中使用了文件来记录RECORD_ID，此时RECODE_ID和cloudflare中的记录就不同了，但是在更新ip的时候会优先读取文件中的ID，就导致的更新的时候报错记录不存在。建议不使用文件来记录ID，仅使用文件记录上次更新IP。
